# Generated by Django 3.0.6 on 2020-05-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konna_web', '0006_auto_20200516_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='content',
            field=models.CharField(max_length=4000),
        ),
    ]
