# Generated by Django 3.0.6 on 2020-05-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konna_web', '0007_auto_20200516_2330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('article', 'content', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='commentreply',
            unique_together={('comment', 'content', 'subject')},
        ),
    ]
