# Generated by Django 3.0.6 on 2020-05-17 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('konna_web', '0010_remove_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 10, 59, 32, 91543, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
